### ISSUE TITLE
Change default language in OSX setup

### ISSUE THREAD

**Issue by adistoica** [Swayyyyy/ASUS-TUF-GAMING-B460M-PLUS-RX570-Hackintosh-Opencore#5]
Hello,

Thanks for creating this pack of files, as I have the same motherboard.
I'm having a small issue where after I boot opencore, the default macos installer language is in Chinese.
How can I change it to English ? (my installer usb was created on a english language macbook)

Thanks

**Comment by Swayyyyy** [comment]
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf

Section 9.4 may helps you

**Comment by adistoica** [comment]
I've solved it by changing the language in the installer menu.
